name: dbt Daily Run
on:
  schedule:
    - cron: '15 3 * * *'  # 3:15 AM UTC
jobs:
  run-dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install dbt-core
      - run: dbt run
